//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Notification_SystemEntities2 : DbContext
    {
        public Notification_SystemEntities2()
            : base("name=Notification_SystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mailQueue> mailQueues { get; set; }
        public virtual DbSet<Notification_tb> Notification_tb { get; set; }
        public virtual DbSet<smsQueue> smsQueues { get; set; }
    }
}
