//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_tb
    {
        public int id { get; set; }
        public string subjec { get; set; }
        public string content { get; set; }
        public string lang { get; set; }
    }
}
